# Generated by Django 2.2.16 on 2020-10-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('entry', models.TextField()),
                ('rating', models.IntegerField()),
                ('picture', models.ImageField(unique=True, upload_to='Feedback/')),
            ],
        ),
        migrations.CreateModel(
            name='ForApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, verbose_name='Адрес почты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, verbose_name='Адрес почты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, verbose_name='Адрес почты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneNumberS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell', models.CharField(max_length=13, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Viber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
