# Generated by Django 2.2.16 on 2020-10-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201021_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='firstwindow',
            options={'verbose_name_plural': 'Первый экран'},
        ),
        migrations.AlterModelOptions(
            name='forapplications',
            options={'verbose_name_plural': 'Почта для отправки уведомлений о заказах'},
        ),
        migrations.AlterModelOptions(
            name='forfeedback',
            options={'verbose_name_plural': 'Почта для отправки уведомлений о отзыве'},
        ),
        migrations.AlterModelOptions(
            name='formailing',
            options={'verbose_name_plural': 'Почта для отправки уведомлений о рассылке'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='secondwindow',
            options={'verbose_name_plural': 'Второй экран'},
        ),
        migrations.AlterModelOptions(
            name='telephonenumbers',
            options={'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='firstwindow',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='forapplications',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='forfeedback',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='formailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='telephonenumbers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='viber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
        migrations.AlterField(
            model_name='secondwindow',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
    ]
