# Generated by Django 2.2.16 on 2020-10-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201022_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно на страницу')),
                ('working_time', models.CharField(max_length=10, verbose_name='Время работы')),
            ],
            options={
                'verbose_name_plural': 'Время работы',
            },
        ),
    ]
