# Generated by Django 2.2.16 on 2020-10-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201022_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно на страницу')),
                ('address', models.EmailField(max_length=254, verbose_name='Адрес почты')),
            ],
            options={
                'verbose_name_plural': 'Почта для отправки уведомлений о обратном звонке',
            },
        ),
        migrations.CreateModel(
            name='Geomarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно на страницу')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name_plural': 'Геометка офиса',
            },
        ),
    ]
