# Generated by Django 2.2.16 on 2020-10-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_forcallback_geomarker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
    ]
