# Generated by Django 2.2.16 on 2020-10-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201023_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgalleryphoto',
            name='product',
        ),
        migrations.AddField(
            model_name='productgalleryphoto',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product'),
        ),
    ]
