# Generated by Django 2.2.16 on 2020-10-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201023_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_packing',
            field=models.IntegerField(choices=[('Мешок', '1'), ('Термоупаковка', '2'), ('Биг Бег', '3'), ('Навал', '4')], default=1, verbose_name='Тип фасовки'),
        ),
    ]
