# Generated by Django 2.2.16 on 2020-10-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_type_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_packing',
            field=models.IntegerField(choices=[(1, 'Мешок'), (2, 'Термоупаковка'), (3, 'Биг Бег'), (4, 'Навал')], default=1, verbose_name='Тип фасовки'),
        ),
    ]
