# Generated by Django 2.2.16 on 2020-10-23 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201023_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 20, 40, 57, 85863)),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 20, 40, 57, 75570)),
        ),
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 20, 40, 57, 85863)),
        ),
    ]
