# Generated by Django 2.2.16 on 2020-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201023_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Product'),
        ),
    ]
