# Generated by Django 2.2.16 on 2020-10-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201023_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalleryphoto',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='productgalleryvideo',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video', to='app.Product'),
        ),
    ]
