# Generated by Django 2.2.16 on 2020-10-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201026_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно на страницу'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Feedback/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tell',
            field=models.CharField(blank=True, max_length=13, verbose_name='Телефон'),
        ),
    ]
