# Generated by Django 2.2.16 on 2020-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201028_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalleryvideo',
            name='preview_link',
            field=models.CharField(default=None, max_length=5000, null=True, verbose_name='Ссылка'),
        ),
    ]
