# Generated by Django 2.2.16 on 2020-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_productgalleryvideo_preview_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalleryvideo',
            name='preview_link',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True, verbose_name='Ссылка на привью'),
        ),
    ]
