# Generated by Django 2.2.16 on 2020-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201103_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='quantity',
            field=models.CharField(blank=True, default='0', max_length=500, null=True, verbose_name='Количество'),
        ),
    ]
