# Generated by Django 2.2.16 on 2020-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_benefits1_benefits2_benefits3_benefits4_benefits5_benefits6_benefits7_benefits8_mainoffice_stylemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits1',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits2',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits3',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits4',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits5',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits6',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits7',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='benefits8',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
    ]
