# Generated by Django 2.2.16 on 2020-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201116_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylemainpage',
            options={'verbose_name_plural': 'Стиль сайта'},
        ),
        migrations.AddField(
            model_name='stylemainpage',
            name='color',
            field=models.CharField(choices=[('', 'Зеленый'), ('pink', 'Термоупаковка'), ('orange', 'Биг Бег')], default='', max_length=20, verbose_name='Цвет'),
        ),
    ]
