# Generated by Django 2.2.16 on 2020-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201116_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylemainpage',
            name='color',
            field=models.CharField(choices=[('', 'Зеленый'), ('pink', 'Розовый'), ('orange', 'Оранжевый')], default='', max_length=20, verbose_name='Цвет'),
        ),
    ]
