# Generated by Django 2.2.16 on 2020-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201116_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomarker',
            name='latitude',
            field=models.CharField(max_length=100, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='geomarker',
            name='longitude',
            field=models.CharField(max_length=100, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mailing_status',
            field=models.BooleanField(default=False, verbose_name='Согласен на рассылку'),
        ),
        migrations.AlterField(
            model_name='stylemainpage',
            name='color',
            field=models.CharField(choices=[('green', 'Зеленый'), ('pink', 'Розовый'), ('orange', 'Оранжевый')], default='', max_length=20, verbose_name='Цвет'),
        ),
    ]
