# Generated by Django 2.2.16 on 2020-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201116_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in processing', 'В обработке'), ('success', 'Успех'), ('refusing', 'Отказ')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='mailing_status',
            field=models.BooleanField(default=False, verbose_name='Согласен на рассылку'),
        ),
        migrations.AlterField(
            model_name='stylemainpage',
            name='color',
            field=models.CharField(choices=[('green', 'Зеленый'), ('pink', 'Розовый'), ('orange', 'Оранжевый')], default='', max_length=20, verbose_name='Цвет'),
        ),
    ]
