# Generated by Django 2.2.16 on 2020-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20201119_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_ready',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата готовности'),
        ),
    ]
