# Generated by Django 2.2.16 on 2020-11-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201119_2358'),
        ('app', '0031_auto_20201120_1246'),
    ]

    operations = [
    ]
