# Generated by Django 2.2.16 on 2021-03-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201119_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='geography',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='География'),
        ),
        migrations.AddField(
            model_name='applications',
            name='note',
            field=models.TextField(default=None, null=True, verbose_name='Заметка'),
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('success', 'Успех'), ('refusing', 'Отказ')], default='new', max_length=30, verbose_name='Статус заявки')),
                ('application', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Applications', verbose_name='Заказ')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявки на обратный звонок',
                'verbose_name_plural': 'Заявка на обратный звонок',
            },
        ),
    ]
