# Generated by Django 2.2.16 on 2021-03-04 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210304_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 22, 50, 30, 547019), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='application',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Applications', verbose_name='Заказ'),
        ),
    ]
