# Generated by Django 2.2.16 on 2021-03-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210304_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
